  <!--#if expr="$REMOTE_ADDR = /139\.19\..*\..*/" -->
      <!-- CORRECT HERE:  -->
      <!-- this is visible only from inside. It's convenient for everyone in the institute -->
      <!-- that way spammers can not harvest your email address -->
      <a href="mailto:unixlogin@mpi-inf.mpg.de">unixlogin@mpi-inf.mpg.de</a><br />
  <!--#else -->
      <!-- CORRECT HERE: Your personal URL is on the people page -->
      <!-- to see how to code the URL for getting your email address, just visit the -->
      <!-- people page and copy the URL (Get email address via email) from your entry there! -->
      <a href="http://www.mpi-inf.mpg.de/people/index.html#unixlogin">Get my email address via email</a><br />
  <!--#endif -->