<!-- include file: menu.inc; start -->
<ul class="linklist">
<li><a href="index.html" accesskey="h" title="Firstname Lastname MPII Homepage" id="hp-index">Firstname Lastname:</a>
<ul>
<li><a href="index.html#research" accesskey="r" title="Research Interests" id="hp-research"><span class="ak">R</span>esearch Interests</a></li>
<li><a href="index.html#publications" accesskey="p" title="Publications of Firstname Lastname" id="hp-publications"><span class="ak">P</span>ublications</a></li>
<li><a href="index.html#teaching" accesskey="t" title="Teaching of Firstname Lastname" id="hp-teaching"><span class="ak">T</span>eaching</a></li>
<li><a href="index.html#positions" accesskey="o" title="Positions of Firstname Lastname" id="hp-positions">Recent P<span class="ak">o</span>sitions</a></li>
<li><a href="index.html#education" accesskey="e" title="Education of Firstname Lastname" id="hp-education"><span class="ak">E</span>ducation</a></li>
<li><a href="index.html#links" accesskey="l" title="Private Stuff of Firstname Lastname"><span class="ak">L</span>inks</a></li>
<li><a href="index.html#private" accesskey="a" title="Private Stuff of Firstname Lastname" id="hp-private"><span class="ak">P</span>rivate</a></li>
</ul>
</li>
<!-- CHANGE HERE: Put your own menu items here. They can also point to different html pages. --> 
<!-- Make sure to highlight the page you are on using the style section on top of that page -->
</ul>
<!-- include file: menu.inc; end -->
